# src/main/resources/application.yml
server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JSESSIONID
        same-site: lax
        http-only: true
        secure: false

spring:
  application:
    name: demo-app
# Redis ?? ? ?? ??

  data:
    redis:
      host: localhost
      port: 16379
      timeout: 2s

  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: spring:session


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:13306/pg-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true&rewriteBatchedStatements=true"
    username: pg
    password: pg1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true